name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2.18
      with:
        variant: "sccache"

    - name: Setup
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x86

    - name: Compile
      run: |
        mkdir bin
        cd bin
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER_LAUNCHER=sccache -D CMAKE_CXX_COMPILER_LAUNCHER=sccache ../
        ninja
        mkdir output_III
        mkdir output_VC
        mkdir output_SA

    - name: Copy built files
      run: |
        cd bin
        cp TrilogyChaosMod.III.asi output_III/TrilogyChaosMod.III.asi
        cp TrilogyChaosMod.VC.asi output_VC/TrilogyChaosMod.VC.asi
        cp TrilogyChaosMod.SA.asi output_SA/TrilogyChaosMod.SA.asi

    - name: Upload III
      uses: actions/upload-artifact@v4
      with:
        name: "TrilogyChaosMod.III"
        path: bin/output_III

    - name: Upload VC
      uses: actions/upload-artifact@v4
      with:
        name: "TrilogyChaosMod.VC"
        path: bin/output_VC

    - name: Upload SA
      uses: actions/upload-artifact@v4
      with:
        name: "TrilogyChaosMod.SA"
        path: bin/output_SA
