name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x86

    - name: Cache bin
      id: cache-bin
      uses: actions/cache@v4
      with:
        path: bin
        key: ${{ runner.os }}-bin

    # Run CMake with caching, disable vcpkg
    - name: Configure and Build
      run: |
        if (!(Test-Path "bin")) {
            mkdir bin
            cd bin
            cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ../
        }
        else {
            make
        }
        ninja -d explain

    - name: Prepare artifacts
      run: |
        cd bin
        if (!(Test-Path "output_III")) { mkdir output_III }
        if (!(Test-Path "output_VC")) { mkdir output_VC }
        if (!(Test-Path "output_SA")) { mkdir output_SA }
        cp TrilogyChaosMod.III.asi output_III/TrilogyChaosMod.III.asi
        cp TrilogyChaosMod.VC.asi output_VC/TrilogyChaosMod.VC.asi
        cp TrilogyChaosMod.SA.asi output_SA/TrilogyChaosMod.SA.asi

    - name: Upload III
      uses: actions/upload-artifact@v4
      with:
        name: "TrilogyChaosMod.III"
        path: bin/output_III

    - name: Upload VC
      uses: actions/upload-artifact@v4
      with:
        name: "TrilogyChaosMod.VC"
        path: bin/output_VC

    - name: Upload SA
      uses: actions/upload-artifact@v4
      with:
        name: "TrilogyChaosMod.SA"
        path: bin/output_SA